// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broadcast/broadcast.proto

package broadcast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Connect struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e28e62ca8000850, []int{0}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Message struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e28e62ca8000850, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Close struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close) Reset()         { *m = Close{} }
func (m *Close) String() string { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()    {}
func (*Close) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e28e62ca8000850, []int{2}
}

func (m *Close) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close.Unmarshal(m, b)
}
func (m *Close) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close.Marshal(b, m, deterministic)
}
func (m *Close) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close.Merge(m, src)
}
func (m *Close) XXX_Size() int {
	return xxx_messageInfo_Close.Size(m)
}
func (m *Close) XXX_DiscardUnknown() {
	xxx_messageInfo_Close.DiscardUnknown(m)
}

var xxx_messageInfo_Close proto.InternalMessageInfo

func (m *Close) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Connect)(nil), "broadcast.Connect")
	proto.RegisterType((*Message)(nil), "broadcast.Message")
	proto.RegisterType((*Close)(nil), "broadcast.Close")
}

func init() { proto.RegisterFile("broadcast/broadcast.proto", fileDescriptor_6e28e62ca8000850) }

var fileDescriptor_6e28e62ca8000850 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0x80, 0x30,
	0x10, 0x85, 0xa9, 0x46, 0x08, 0x17, 0x07, 0xd2, 0xc1, 0x00, 0x0e, 0x6a, 0x27, 0x27, 0x30, 0xb2,
	0xb1, 0x49, 0x67, 0x13, 0x83, 0x9b, 0x0b, 0x29, 0x70, 0xa2, 0xd1, 0x52, 0xd2, 0xd6, 0x5f, 0xe0,
	0x1f, 0x37, 0x68, 0x29, 0x0c, 0x6e, 0xd7, 0x7b, 0x7d, 0xef, 0xbe, 0x3c, 0xc8, 0x7a, 0xad, 0xc4,
	0x38, 0x08, 0x63, 0x4b, 0x3f, 0x15, 0x8b, 0x56, 0x56, 0xd1, 0xd8, 0x2f, 0xd8, 0x25, 0x44, 0x5c,
	0xcd, 0x33, 0x0e, 0x96, 0x26, 0x70, 0xfa, 0xf5, 0x3e, 0xa6, 0xe4, 0x9a, 0xdc, 0xc6, 0xed, 0x3a,
	0xb2, 0x0a, 0xa2, 0x47, 0x34, 0x46, 0x4c, 0x48, 0x2f, 0x20, 0x34, 0x38, 0x8f, 0xa8, 0x9d, 0xee,
	0x5e, 0xab, 0x49, 0x9a, 0x29, 0x3d, 0xf9, 0x33, 0x49, 0x33, 0xb1, 0x0c, 0xce, 0xf8, 0xa7, 0x32,
	0xb8, 0x49, 0xc4, 0x4b, 0xf7, 0xdf, 0x04, 0xe2, 0x66, 0x3b, 0x4d, 0x6b, 0x38, 0xe7, 0x1a, 0x85,
	0xc5, 0x67, 0xab, 0x51, 0x48, 0x4a, 0x8b, 0x9d, 0xd3, 0x31, 0xe5, 0xc7, 0x9d, 0x43, 0x61, 0xc1,
	0x1d, 0xa1, 0x35, 0x24, 0x3e, 0x68, 0x43, 0xfc, 0xe7, 0x6f, 0x9e, 0x1c, 0x33, 0x57, 0x2a, 0x16,
	0x34, 0x37, 0x2f, 0x57, 0xaf, 0xe2, 0x03, 0x8b, 0x41, 0xc9, 0xb2, 0x7d, 0xe2, 0x1d, 0x7f, 0x13,
	0xb6, 0x7b, 0x58, 0x96, 0xbd, 0xa6, 0x3e, 0xfc, 0xed, 0xa9, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0xd7, 0xb9, 0x9a, 0x44, 0x01, 0x00, 0x00,
}
